//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\chris\Downloads\BOM_auslesen.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: chris
//              Version: NX 1996
//              Date: 02-25-2026  (Format: mm-dd-yyyy)
//              Time: 18:05 (Format: hh-mm)
//
//==============================================================================

using System;
using NXOpen;
using NXOpen.BlockStyler;
using System.Collections.Generic;
using System.IO;
using System.Text;

public class BOM_auslesen
{
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.Group group0;
    private NXOpen.BlockStyler.Button button0;
    private bool exportBomRequested = false;

    public BOM_auslesen()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = @"C:\Users\chris\Downloads\BOM_auslesen.dlx";
            theDialog = theUI.CreateDialog(theDlxFileName);
            theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
            theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception ex)
        {
            throw ex;
        }
    }

    public static void Main()
    {
        BOM_auslesen theBOM_auslesen = null;
        try
        {
            theBOM_auslesen = new BOM_auslesen();
            theBOM_auslesen.Show();
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            if (theBOM_auslesen != null)
                theBOM_auslesen.Dispose();
            theBOM_auslesen = null;
        }
    }

    public static int GetUnloadOption(string arg)
    {
        return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
    }

    public static void UnloadLibrary(string arg)
    {
        try
        {
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    public NXOpen.UIStyler.DialogResponse Show()
    {
        try
        {
            theDialog.Show();
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }

    public void Dispose()
    {
        if (theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }

    public void initialize_cb()
    {
        try
        {
            group0 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group0");
            button0 = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button0");
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    public void dialogShown_cb()
    {
        try
        {
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }

    public int apply_cb()
    {
        int errorCode = 0;
        try
        {
        }
        catch (Exception ex)
        {
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }

    public int update_cb(NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            if (block == button0)
            {
                exportBomRequested = true;
            }
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show(
                "Block Styler",
                NXMessageBox.DialogType.Error,
                ex.ToString());
        }

        return 0;
    }

    public int ok_cb()
    {
        int errorCode = 0;

        try
        {
            if (exportBomRequested)
            {
                ExportBomToCsv();
            }
        }
        catch (Exception ex)
        {
            errorCode = 1;
            theUI.NXMessageBox.Show(
                "Block Styler",
                NXMessageBox.DialogType.Error,
                ex.ToString());
        }

        return errorCode;
    }

    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist = null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }

    private void ExportBomToCsv()
    {
        NXOpen.Part workPart = theSession.Parts.Work;

        if (workPart == null)
        {
            theUI.NXMessageBox.Show(
                "Info",
                NXMessageBox.DialogType.Information,
                "Kein aktives Bauteil.");
            return;
        }

        List<BomEntry> bomList = new List<BomEntry>();

        // Einzelteil
        if (workPart.ComponentAssembly.RootComponent == null)
        {
            string partId = GetAttributeValue(workPart, "PART_ID");
            string material = GetMaterial(workPart);

            bomList.Add(new BomEntry
            {
                Name = workPart.Name,
                File = workPart.FullPath,
                PartID = partId,
                Material = material
            });
        }
        else
        {
            // Baugruppe
            TraverseComponent(workPart.ComponentAssembly.RootComponent, bomList);
        }

        StringBuilder sb = new StringBuilder();

        // CSV-Header
        sb.AppendLine("Name;File;PartID;Material");

        foreach (BomEntry item in bomList)
        {
            sb.AppendLine(
                EscapeCsv(item.Name) + ";" +
                EscapeCsv(item.File) + ";" +
                EscapeCsv(item.PartID) + ";" +
                EscapeCsv(item.Material)
            );
        }

        string savePath = @"C:\Users\chris\Desktop\bom.csv";
        File.WriteAllText(savePath, sb.ToString(), Encoding.UTF8);

        theUI.NXMessageBox.Show(
            "Fertig",
            NXMessageBox.DialogType.Information,
            "BOM als CSV gespeichert:\n" + savePath);
    }

    private void TraverseComponent(NXOpen.Assemblies.Component comp, List<BomEntry> list)
    {
        if (comp == null) return;
        if (comp.Prototype == null) return;

        NXOpen.BasePart basePart = comp.Prototype.OwningPart;
        NXOpen.Part part = basePart as NXOpen.Part;

        if (part != null)
        {
            string partId = GetAttributeValue(part, "PART_ID");
            string material = GetMaterial(part);

            list.Add(new BomEntry
            {
                Name = comp.DisplayName,
                File = part.FullPath,
                PartID = partId,
                Material = material
            });
        }

        NXOpen.Assemblies.Component[] children = comp.GetChildren();
        if (children == null) return;

        foreach (NXOpen.Assemblies.Component child in children)
        {
            TraverseComponent(child, list);
        }
    }

    private string GetMaterial(NXOpen.Part part)
    {
        if (part == null) return "";

        // Häufige Attributnamen prüfen
        string[] possibleNames = new string[]
        {
            "MATERIAL",
            "Material",
            "MATATERIAL",
            "WERKSTOFF",
            "Werkstoff"
        };

        foreach (string attrName in possibleNames)
        {
            string value = GetAttributeValue(part, attrName);
            if (!string.IsNullOrEmpty(value))
                return value;
        }

        return "";
    }

    private string GetAttributeValue(NXOpen.NXObject obj, string attributeName)
    {
        if (obj == null || string.IsNullOrEmpty(attributeName))
            return "";

        try
        {
            if (obj.HasUserAttribute(attributeName, NXObject.AttributeType.String, -1))
                return obj.GetStringAttribute(attributeName);
        }
        catch
        {
        }

        try
        {
            if (obj.HasUserAttribute(attributeName, NXObject.AttributeType.Integer, -1))
                return obj.GetIntegerAttribute(attributeName).ToString();
        }
        catch
        {
        }

        try
        {
            if (obj.HasUserAttribute(attributeName, NXObject.AttributeType.Real, -1))
                return obj.GetRealAttribute(attributeName).ToString();
        }
        catch
        {
        }

        return "";
    }

    private string EscapeCsv(string value)
    {
        if (value == null)
            return "\"\"";

        string escaped = value.Replace("\"", "\"\"");
        return "\"" + escaped + "\"";
    }

    public class BomEntry
    {
        public string Name { get; set; }
        public string File { get; set; }
        public string PartID { get; set; }
        public string Material { get; set; }
    }
}