//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\chris\Downloads\BOM_auslesen.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: chris
//              Version: NX 1996
//              Date: 02-25-2026  (Format: mm-dd-yyyy)
//              Time: 18:05 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using NXOpen;
using NXOpen.BlockStyler;
using System.Collections.Generic;
using System.IO;


//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class BOM_auslesen
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theDialog;
    private NXOpen.BlockStyler.Group group0;
    private NXOpen.BlockStyler.Button button0;// Block type: Button
    private bool exportBomRequested = false;

    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public BOM_auslesen()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = @"C:\Users\chris\Downloads\BOM_auslesen.dlx";
            theDialog = theUI.CreateDialog(theDlxFileName);
            theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
            theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
            theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------- DIALOG LAUNCHING ---------------------------------
    //
    //    Before invoking this application one needs to open any part/empty part in NX
    //    because of the behavior of the blocks.
    //
    //    Make sure the dlx file is in one of the following locations:
    //        1.) From where NX session is launched
    //        2.) $UGII_USER_DIR/application
    //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    //            recommended. This variable is set to a full directory path to a file 
    //            containing a list of root directories for all custom applications.
    //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
    //
    //    You can create the dialog using one of the following way:
    //
    //    1. Journal Replay
    //
    //        1) Replay this file through Tool->Journal->Play Menu.
    //
    //    2. USER EXIT
    //
    //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    //        2) Invoke the Shared Library through File->Execute->NX Open menu.
    //
    //------------------------------------------------------------------------------
    public static void Main()
    {
        BOM_auslesen theBOM_auslesen = null;
        try
        {
            theBOM_auslesen = new BOM_auslesen();
            // The following method shows the dialog immediately
            theBOM_auslesen.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        finally
        {
            if(theBOM_auslesen != null)
                theBOM_auslesen.Dispose();
                theBOM_auslesen = null;
        }
    }
    //------------------------------------------------------------------------------
    // This method specifies how a shared image is unloaded from memory
    // within NX. This method gives you the capability to unload an
    // internal NX Open application or user  exit from NX. Specify any
    // one of the three constants as a return value to determine the type
    // of unload to perform:
    //
    //
    //    Immediately : unload the library as soon as the automation program has completed
    //    Explicitly  : unload the library from the "Unload Shared Image" dialog
    //    AtTermination : unload the library when the NX session terminates
    //
    //
    // NOTE:  A program which associates NX Open applications with the menubar
    // MUST NOT use this option since it will UNLOAD your NX Open application image
    // from the menubar.
    //------------------------------------------------------------------------------
     public static int GetUnloadOption(string arg)
    {
        //return System.Convert.ToInt32(Session.LibraryUnloadOption.Explicitly);
         return System.Convert.ToInt32(Session.LibraryUnloadOption.Immediately);
        // return System.Convert.ToInt32(Session.LibraryUnloadOption.AtTermination);
    }
    
    //------------------------------------------------------------------------------
    // Following method cleanup any housekeeping chores that may be needed.
    // This method is automatically called by NX.
    //------------------------------------------------------------------------------
    public static void UnloadLibrary(string arg)
    {
        try
        {
            //---- Enter your code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //This method shows the dialog on the screen
    //------------------------------------------------------------------------------
    public NXOpen.UIStyler.DialogResponse Show()
    {
        try
        {
            theDialog.Show();
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if(theDialog != null)
        {
            theDialog.Dispose();
            theDialog = null;
        }
    }
    
    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            group0 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group0");
            button0 = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("button0");
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: apply_cb
    //------------------------------------------------------------------------------
    public int apply_cb()
    {
        int errorCode = 0;
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            errorCode = 1;
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return errorCode;
    }

    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb(NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            if (block == button0)
            {
                exportBomRequested = true;
            }
        }
        catch (Exception ex)
        {
            theUI.NXMessageBox.Show(
                "Block Styler",
                NXMessageBox.DialogType.Error,
                ex.ToString());
        }

        return 0;
    }

    //------------------------------------------------------------------------------
    //Callback Name: ok_cb
    //------------------------------------------------------------------------------
    public int ok_cb()
    {
        int errorCode = 0;

        try
        {
            if (exportBomRequested)
            {
                ExportBomToJson();
            }
        }
        catch (Exception ex)
        {
            errorCode = 1;
            theUI.NXMessageBox.Show(
                "Block Styler",
                NXMessageBox.DialogType.Error,
                ex.ToString());
        }

        return errorCode;
    }

    //------------------------------------------------------------------------------
    //Function Name: GetBlockProperties
    //Returns the propertylist of the specified BlockID
    //------------------------------------------------------------------------------
    public PropertyList GetBlockProperties(string blockID)
    {
        PropertyList plist =null;
        try
        {
            plist = theDialog.GetBlockProperties(blockID);
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return plist;
    }



    private void ExportBomToJson()
    {
        NXOpen.Part workPart = theSession.Parts.Work;

        if (workPart == null)
        {
            theUI.NXMessageBox.Show(
                "Info",
                NXMessageBox.DialogType.Information,
                "Kein aktives Bauteil.");
            return;
        }

        List<BomEntry> bomList = new List<BomEntry>();

        // Single part case
        if (workPart.ComponentAssembly.RootComponent == null)
        {
            string partId = "";

            if (workPart.HasUserAttribute("PART_ID", NXObject.AttributeType.String, -1))
            {
                partId = workPart.GetStringAttribute("PART_ID"); // Warning ok
            }

            bomList.Add(new BomEntry
            {
                Name = workPart.Name,
                File = workPart.FullPath,
                PartID = partId
            });
        }
        else
        {
            // Assembly-Fall
            TraverseComponent(workPart.ComponentAssembly.RootComponent, bomList);
        }

        // Manually create JSON (with escaping)
        System.Text.StringBuilder sb = new System.Text.StringBuilder();
        sb.AppendLine("[");
        for (int i = 0; i < bomList.Count; i++)
        {
            BomEntry item = bomList[i];

            sb.AppendLine("  {");
            sb.AppendLine("    \"Name\": \"" + EscapeJson(item.Name) + "\",");
            sb.AppendLine("    \"File\": \"" + EscapeJson(item.File) + "\",");
            sb.AppendLine("    \"PartID\": \"" + EscapeJson(item.PartID) + "\"");
            sb.Append("  }");

            if (i < bomList.Count - 1) sb.Append(",");
            sb.AppendLine();
        }
        sb.AppendLine("]");

        string savePath = @"C:\Users\chris\Desktop\bom.json";
        File.WriteAllText(savePath, sb.ToString());

        theUI.NXMessageBox.Show(
            "Fertig",
            NXMessageBox.DialogType.Information,
            "BOM gespeichert:\n" + savePath);
    }

    private void TraverseComponent(NXOpen.Assemblies.Component comp, List<BomEntry> list)
    {
        if (comp == null) return;

        // Prototype may be null depending on the situation
        if (comp.Prototype == null) return;

        NXOpen.BasePart basePart = comp.Prototype.OwningPart;
        NXOpen.Part part = basePart as NXOpen.Part;

        if (part != null)
        {
            string partId = "";

            if (part.HasUserAttribute("PART_ID", NXObject.AttributeType.String, -1))
            {
                partId = part.GetStringAttribute("PART_ID"); // Error ok
            }

            list.Add(new BomEntry
            {
                Name = comp.DisplayName,
                File = part.FullPath,
                PartID = partId
            });
        }

        NXOpen.Assemblies.Component[] children = comp.GetChildren();
        if (children == null) return;

        foreach (NXOpen.Assemblies.Component child in children)
        {
            TraverseComponent(child, list);
        }
    }
    private string EscapeJson(string s)
    {
        if (s == null) return "";
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    public class BomEntry
    {
        public string Name { get; set; }
        public string File { get; set; }
        public string PartID { get; set; }
    }
    
}
